baseURL = "https://danielkleviansky.com/"
languageCode = "en-au"
title = "Daniel Kleviansky"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[params]
  author = "Daniel Kleviansky"
  description = "Part of the Human Network"
  images = ["/profile.jpg"]
  defaultTheme = "auto"        # auto, light, or dark
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = false
  hideFooter = false

  [params.assets]
    favicon         = "favicon.svg"
    favicon16x16    = "favicon.svg"
    favicon32x32    = "favicon.svg"

  [params.profileMode]
    enabled = true
    title = "Daniel Kleviansky"
    subtitle = "Software Engineer · System Architect · Technical Lead"
    imageUrl = "/profile.jpg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Daniel Kleviansky"

  [[params.profileMode.buttons]]
    name = "About"
    url = "/about/"

  [[params.profileMode.buttons]]
    name = "Music"
    url = "/music/"

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

  [[params.profileMode.buttons]]
    name = "Résumé"
    url = "/resume/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kleviansky/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/lqid"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/user/danklev/"

  [[params.socialIcons]]
    name = "spotify"
    url = "https://open.spotify.com/artist/33gK9iubv5jGA9Gg27wIkY"

  [[params.socialIcons]]
    name = "applemusic"
    url = "https://music.apple.com/au/artist/daniel-kleviansky/1510186994"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://facebook.com/DanielKlevianskyAU"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 15
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 17
  [[menu.main]]
    name = "Résumé"
    url = "/resume/"
    weight = 20

[markup]
  [markup.goldmark.renderer]
    unsafe = true   # allows raw HTML in Markdown if needed
