baseURL = "https://danielkleviansky.com/"
languageCode = "en-au"
title = "Daniel Kleviansky"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[params]
  author = "Daniel Kleviansky"
  description = "Part of the Human Network"
  images = ["/profile.jpg"]
  defaultTheme = "auto"        # auto, light, or dark
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = false
  hideFooter = false

  [params.assets]
    favicon         = "favicon.svg"
    favicon16x16    = "favicon.svg"
    favicon32x32    = "favicon.svg"

  [params.profileMode]
    enabled = true
    title = "Daniel Kleviansky"
    subtitle = "Software Engineer · System Architect · Technical Lead"
    imageUrl = "/profile.jpg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Daniel Kleviansky"

  [[params.profileMode.buttons]]
    name = "Writing"
    url = "/writing/"

  [[params.profileMode.buttons]]
    name = "Now"
    url = "/now/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:daniel@kleviansky.com"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kleviansky/"

  [[params.socialIcons]]
    name = "spotify"
    url = "https://open.spotify.com/artist/33gK9iubv5jGA9Gg27wIkY"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 13
  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 15
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 17
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 18
  [[menu.main]]
    name = "Résumé"
    url = "/resume/"
    weight = 20

[markup]
  [markup.goldmark.renderer]
    unsafe = true   # allows raw HTML in Markdown if needed
